package ar.edu.unlam.dominio.enums;

public enum Filo {
	
	ANNELIDA, ARTHROPODA, BRACHIOPODA, BRYOZOA, CHAETOGNATHA, CHORDATA, CNIDARIA, CTENOPHORA, CYCLIOPHORA, ECHINODERMATA, ENTOPROCTA, GASTROTRICHA, GNATHOSTOMULIDA, HEMICHORDATA, KINORHYNCHA, LORICIFERA, MICROGNATHOZOA, MOLLUSCA, NEMATODA, NEMATOMORPHA, NEMERTHEA, ONYCHOPHORA, PHORONIDA, PLACOZOA, PLATYHELMINTHES, PORIFERA, PRIAPULIDA, RHOMBOZOA, ROTIFERA, TARDIGRADA, XENACOELOMORPHA

}
